title: Ural-PDC
description: Ural Workshop on Parallel, Distributed, and Cloud Computing for Young Scientists.
email: avs@imm.uran.ru
baseurl: ''
url: http://ural-pdc.org
markdown: kramdown
sass:
  style: compressed
exclude:
- Gemfile*
- README.md
- LICENSE.txt
gems:
- jekyll-sitemap
whitelist:
- jekyll-sitemap
safe: true
timezone: Asia/Yekaterinburg
encoding: UTF-8
recent: '2016'
